#!/bin/bash
# cmdlist: show allowed commands and their descriptions (wrapper)

cat <<'EOF'
Allowed commands:

cat       - concatenate files and print on the standard output
date      - print or set the system date and time
edged     - Display Edge service version and information.
grep      - print lines that match patterns
ifstat    - handy utility to read network interface statistics
ls        - list directory contents
uptime    - Tell how long the system has been running.
whoami    - print effective userid

Allowed wrappers commands:

debugpy   - Run debug.py wrapper script (restricted options only)
cmdlist   - show allowed commands and their descriptions

EOF
